theme: minima
title: Dat's Science
author: Krystyna
email: krysia.stepniewska@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You will see lots of awsome examples of cool data visuals here

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Krystep # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
